name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -f src/main/docker/Dockerfile.jvm -t kescatefou/organisations-service .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push kescatefou/organisations-service:latest

      - name: Deploy to Portainer
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.PORTAINER_API_KEY }}" \
          https://portainer.leonaar.com/api/stacks/organisations-service/restart
      
